import { Inter, Poppins, Roboto, Montserrat, Josefin_Sans, Acme } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({weight: "700", subsets: ["latin"]});
export const metadata = {
  title: "shortly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
